version: "3"
services:
  querier:
    image: emission/test-querier:latest
    environment:
      - WEB_SERVER_HOST=0.0.0.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      #ENV VAR FOR RUNTIME PORT MAPPING
      - $PORTMAP
    networks:
      - emission
