version: "3"
services:
  web-server:
    image: emission/test-last-event:1.0
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      #ENV VAR FOR RUNTIME PORT MAPPING
        - $PORTMAP
    links:
      - db:db$ctr
    networks:
      - emission
networks:
  emission:
    external: True
