version: "3"
services:
  count:
    image: e-mission/count:1.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      #ENV VAR FOR RUNTIME PORT MAPPING
        - $PORTMAP
    networks:
      - emission
networks:
  emission:
    external: True
